# Generated by Django 6.0.5 on 2026-05-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florapy', '0001_initial'),
        ('pylogenyapp', '0002_alter_taxonomicrank_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateField(verbose_name='Visit date')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='florapy.locality', verbose_name='Locality')),
                ('taxa', models.ManyToManyField(blank=True, related_name='locality_visits', to='pylogenyapp.taxon', verbose_name='Taxa')),
            ],
            options={
                'verbose_name': 'Locality visit',
                'verbose_name_plural': 'Locality visits',
                'ordering': ['-visited_at', 'locality'],
            },
        ),
    ]
