# Generated by Django 6.0.5 on 2026-05-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florapy', '0002_localityvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityvisit',
            options={},
        ),
    ]
