# Generated by Django 6.0.6 on 2026-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0003_alter_localityvisit_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Project name"
                    ),
                ),
            ],
        ),
    ]
