# Generated by Django 6.0.6 on 2026-07-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0004_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="project_name",
        ),
    ]
