# Generated by Django 6.0.6 on 2026-07-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0005_rename_name_project_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localities",
                to="florapy.project",
                verbose_name="Project",
            ),
        ),
    ]
