# Generated by Django 6.0.6 on 2026-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0006_locality_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["project_name"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
