# Generated by Django 6.0.6 on 2026-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0007_alter_project_options_project_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="conservation_issues",
            field=models.TextField(blank=True, verbose_name="Conservation issues"),
        ),
        migrations.AddField(
            model_name="locality",
            name="ecological_indicator_assessment",
            field=models.TextField(
                blank=True, verbose_name="Ecological indicator assessment"
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="habitat_description",
            field=models.TextField(blank=True, verbose_name="Habitat description"),
        ),
        migrations.AddField(
            model_name="locality",
            name="locality_description",
            field=models.TextField(blank=True, verbose_name="Locality description"),
        ),
    ]
