# Generated by Django 6.0.6 on 2026-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0008_locality_conservation_issues_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locality",
            name="locality_description",
        ),
        migrations.AddField(
            model_name="locality",
            name="geographical_location_description",
            field=models.TextField(
                blank=True, verbose_name="Geographical location description"
            ),
        ),
    ]
