# Generated by Django 6.0.6 on 2026-07-13 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0009_remove_locality_locality_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="reference_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Reference point"
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="reference_point_description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Reference point description"
            ),
        ),
    ]
