# Generated by Django 6.0.6 on 2026-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0010_locality_reference_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="polygon_description",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Polygon description",
            ),
        ),
    ]
