# Generated by Django 6.0.6 on 2026-07-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("florapy", "0011_locality_polygon_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locality",
            name="habitat_description",
        ),
    ]
