# Generated by Django 6.0.5 on 2026-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cs', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.SlugField(help_text='For example: species, genus, family, order', max_length=100, unique=True, verbose_name='Code')),
                ('level', models.PositiveSmallIntegerField(help_text='Lower number means a more general rank. For example: kingdom = 20, species = 80.', unique=True, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Taxonomic rank',
                'verbose_name_plural': 'Taxonomic ranks',
                'ordering': ['level'],
            },
        ),
    ]
