# Generated by Django 6.0.5 on 2026-05-20 09:25

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylogenyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomicrank',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='Lower number means a more general rank.', unique=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='taxonomicrank',
            name='name_cs',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name czech'),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cs', models.CharField(max_length=255, verbose_name='Name czech')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Scientific name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pylogenyapp.taxon', verbose_name='Parent taxon')),
                ('taxonomic_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxa', to='pylogenyapp.taxonomicrank', verbose_name='Taxonomic rank')),
            ],
            options={
                'verbose_name': 'Taxon',
                'verbose_name_plural': 'Taxa',
                'ordering': ['tree_id', 'lft'],
                'constraints': [models.UniqueConstraint(fields=('scientific_name', 'taxonomic_rank', 'parent'), name='unique_taxon_scientific_name_rank_parent')],
            },
        ),
    ]
