# Generated by Django 6.0.5 on 2026-06-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0002_alter_taxonomicrank_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameAuthorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="name authorship"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="year of publication"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
            ],
            options={
                "verbose_name": "name authorship",
                "verbose_name_plural": "name authorships",
                "ordering": ["text", "year"],
            },
        ),
        migrations.AddField(
            model_name="taxon",
            name="authorship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taxa",
                to="pylogenyapp.nameauthorship",
                verbose_name="name authorship",
            ),
        ),
    ]
