# Generated by Django 6.0.6 on 2026-07-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0003_nameauthorship_taxon_authorship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameauthorship",
            name="text",
            field=models.CharField(max_length=255, verbose_name="name authorship"),
        ),
    ]
