# Generated by Django 6.0.6 on 2026-07-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0004_alter_nameauthorship_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nameauthorship",
            unique_together={("text", "year")},
        ),
    ]
