# Generated by Django 6.0.6 on 2026-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0005_alter_nameauthorship_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzechRedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Czech red list",
                "verbose_name_plural": "Czech red lists",
                "ordering": ["code"],
            },
        ),
    ]
