# Generated by Django 6.0.6 on 2026-07-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0006_czechredlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="czech_red_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pylogenyapp.czechredlist",
            ),
        ),
    ]
