# Generated by Django 6.0.6 on 2026-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0007_taxon_czech_red_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzechLegalProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        help_text="Legal protection category paragraph, e.g. §1, §2, §3.",
                        max_length=10,
                        unique=True,
                        verbose_name="paragraph",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the legal protection category.",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Czech legal protection category",
                "verbose_name_plural": "Czech legal protection categories",
                "ordering": ["paragraph"],
            },
        ),
    ]
