# Generated by Django 6.0.6 on 2026-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0009_taxon_czech_legal_protection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzechTaxonOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Origin"
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxon origin in Czechia",
                "verbose_name_plural": "Taxon origins in Czechia",
                "ordering": ["origin"],
            },
        ),
        migrations.CreateModel(
            name="InvasiveStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invasive status",
                "verbose_name_plural": "Invasive statuses",
                "ordering": ["status"],
            },
        ),
    ]
