# Generated by Django 6.0.6 on 2026-07-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0010_czechtaxonorigin_invasivestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="czech_taxon_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pylogenyapp.czechtaxonorigin",
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="invasive_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pylogenyapp.invasivestatus",
            ),
        ),
    ]
