# Generated by Django 6.0.6 on 2026-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0011_taxon_czech_taxon_origin_taxon_invasive_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EllenbergIndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "light_description",
                    models.CharField(
                        help_text="L: Indicator values for light",
                        max_length=255,
                        verbose_name="Light value description",
                    ),
                ),
                (
                    "temperature_description",
                    models.CharField(
                        help_text="T: Indicator values for temperature",
                        max_length=255,
                        verbose_name="Temperature value description",
                    ),
                ),
                (
                    "moisture_description",
                    models.CharField(
                        help_text="M: Indicator values for moisture",
                        max_length=255,
                        verbose_name="Moisture value description",
                    ),
                ),
                (
                    "reaction_description",
                    models.CharField(
                        help_text="R: Indicator values for reaction",
                        max_length=255,
                        verbose_name="Reaction value description",
                    ),
                ),
                (
                    "nutrients_description",
                    models.CharField(
                        help_text="N: Indicator values for nutrients",
                        max_length=255,
                        verbose_name="Nutrients value description",
                    ),
                ),
                (
                    "salinity_description",
                    models.CharField(
                        help_text="S: Indicator values for salinity",
                        max_length=255,
                        verbose_name="Salinity value description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ellenberg indicator value",
                "verbose_name_plural": "Ellenberg indicator values",
            },
        ),
    ]
