# Generated by Django 6.0.6 on 2026-07-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0013_taxon_ellenberg_indicator_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="ellenberg_indicator_values",
        ),
    ]
