# Generated by Django 6.0.6 on 2026-07-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0014_remove_taxon_ellenberg_indicator_values"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EllenbergIndicatorValue",
        ),
    ]
