# Generated by Django 6.0.6 on 2026-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0015_delete_ellenbergindicatorvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="EllenbergIndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "light",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="L: Indicator values for light",
                        null=True,
                        verbose_name="Light",
                    ),
                ),
                (
                    "temperature",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="T: Indicator values for temperature",
                        null=True,
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "moisture",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="M: Indicator values for moisture",
                        null=True,
                        verbose_name="Moisture",
                    ),
                ),
                (
                    "reaction",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="R: Indicator values for reaction",
                        null=True,
                        verbose_name="Reaction",
                    ),
                ),
                (
                    "nutrients",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="N: Indicator values for nutrients",
                        null=True,
                        verbose_name="Nutrients",
                    ),
                ),
                (
                    "salinity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="S: Indicator values for salinity",
                        null=True,
                        verbose_name="Salinity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ellenberg indicator value",
                "verbose_name_plural": "Ellenberg indicator values",
            },
        ),
    ]
