# Generated by Django 6.0.6 on 2026-07-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylogenyapp", "0016_ellenbergindicatorvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="ellenberg_indicator_values",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pylogenyapp.ellenbergindicatorvalue",
            ),
        ),
    ]
